/**
 * User-visible strings of the core and the renderers. English is complete;
 * German covers the same keys. Vocabulary follows the workbench rules:
 * "priority", "expectation shortfall", never "root cause", "fault" or "effect".
 */
import type { Locale } from "./format.js";

const en = {
  "kind.activity": "activity",
  "kind.stage": "stage",
  "kind.gateway": "gateway",
  "kind.event": "event",
  "kind.note": "note",
  "kind.follows": "path",
  "kind.constraint": "constraint",
  "kind.flow": "sequence flow",
  "group.lane": "lane",
  "group.stage": "stage",
  "group.pool": "pool",
  "map.description": "Process map with {nodes} activities and {edges} paths in {groups} groups.",
  "map.abstraction": "Abstraction: activities above {nodeShare}, paths above {edgeShare}.",
  "map.overlays": "{count} constraint overlays.",
  "map.selected": "Selected: {label}.",
  "map.reconnected": "re-added to keep the map connected",
  "metric.events": "events",
  "metric.cases": "cases",
  "metric.count": "transitions",
  "metric.share": "share",
  "metric.violationShare": "expectation shortfall",
  "metric.medianLagHours": "median lag",
  "metric.p90LagHours": "90th percentile lag",
  "metric.medianNextHours": "median time to next event",
  "metric.starts": "case starts",
  "metric.ends": "case ends",
  "metric.internalCount": "transitions inside the stage",
  "metric.members": "activities",
  "metric.delta": "difference",
  "controls.title": "Abstraction",
  "controls.activities": "Activities",
  "controls.paths": "Paths",
  "controls.collapse": "Show stages",
  "controls.expand": "Show activities",
  "controls.connected": "Keep connected",
  "controls.table": "Table view",
  "controls.map": "Map view",
  "legend.title": "Legend",
  "legend.edgeWidth": "Path width",
  "legend.edgeColor": "Path colour",
  "legend.nodeColor": "Activity colour",
  "legend.reconnected": "Re-added path",
  "legend.outOfScope": "Outside scope",
  "legend.badge": "Constraint badge with shortfall share",
  "legend.arc": "Lag or precedence arc; width = coverage, colour = shortfall",
  "legend.reverse": "Reverse-order arc (precedence violated)",
  "legend.selfLoop": "Repeated execution",
  "overlay.badge": "badge",
  "overlay.arc": "arc",
  "overlay.hatch": "hatch",
  "overlay.tint": "tint",
  "overlay.chip": "chip",
  "overlay.selfLoop": "self-loop",
  "constraint.presence": "presence",
  "constraint.singularity": "singularity",
  "constraint.exclusion": "exclusion",
  "constraint.lag": "lag",
  "constraint.precedence": "precedence",
  "constraint.balance": "balance",
  "constraint.metric": "metric",
  "constraint.applicability": "applicability",
  "constraint.missing": "{share} missing",
  "constraint.repeated": "{share} repeated",
  "constraint.occurs": "{share} occur",
  "constraint.late": "{share} late",
  "constraint.reverse": "{share} in reverse order",
  "constraint.coverage": "{share} of cases evaluated",
  "constraint.median": "median {value}",
  "constraint.threshold": "threshold {value}",
  "constraint.above": "{share} above threshold",
  "constraint.outOfScope": "outside scope",
  "constraint.scope": "applies to {share} of cases",
  "constraint.notApplicable": "not applicable in this scene",
  "table.nodes": "Activities",
  "table.edges": "Paths",
  "table.overlays": "Constraint overlays",
  "table.caption.nodes": "Activities of the process map with their metrics",
  "table.caption.edges": "Paths of the process map with their metrics",
  "table.caption.overlays": "Constraint overlays with the numbers they encode",
  "table.label": "Label",
  "table.kind": "Kind",
  "table.group": "Group",
  "table.source": "From",
  "table.target": "To",
  "table.overlay": "Overlay",
  "table.target.column": "Target",
  "table.constraint": "Constraint",
  "table.value": "Value",
  "table.text": "Reading",
  "table.tags": "Tags",
  "table.empty": "Nothing to show.",
  "timeline.description": "Trace timeline with {traces} cases and {events} events.",
  "timeline.anchor": "aligned at {anchor}",
  "timeline.case": "Case",
  "timeline.time": "Time",
  "timeline.activity": "Activity",
  "timeline.violates": "Violates",
  "timeline.days": "days",
  "timeline.hours": "hours",
  "export.context": "{label} · {cases} cases · {events} events",
  "bpmn.description": "BPMN diagram with {tasks} tasks, {gateways} gateways and {flows} sequence flows in {lanes} lanes.",
  "bpmn.diagram": "Diagram view",
  "bpmn.table": "Table view",
  "bpmn.loading": "Loading the diagram…",
  "bpmn.error": "The diagram could not be loaded.",
  "bpmn.selected": "Selected: {tasks} tasks, {flows} flows, {lanes} lanes.",
  "bpmn.mode.view": "View",
  "bpmn.mode.model": "Model",
  "views.title": "Views",
  "views.single": "One view",
  "views.grid": "All views",
  "views.shared": "Colour and width scales are shared across the views.",
  "map.instructions": "Use the arrow keys to move between activities, Space to select, Shift with an arrow key to extend the selection, Alt with an arrow key to move along paths, Enter to open the actions menu, Escape to clear the selection.",
  "map.focus": "Paths of {label} are shown; unrelated activities are dimmed.",
  "map.focusPair": "The path between {a} and {b} is shown; unrelated activities are dimmed.",
  "map.renderer.canvas": "Drawn on a canvas because of its size: {nodes} activities and {edges} paths.",
  "map.zoomIn": "Zoom in",
  "map.zoomOut": "Zoom out",
  "map.fit": "Fit the map",
  "map.focused": "Focused: {label}.",
  "selection.none": "Selection cleared.",
  "selection.one": "Selected: {label}.",
  "selection.pair": "Selected: {a} and {b}.",
  "selection.set": "Selected: {count} activities: {labels}.",
  "selection.edge": "Selected: path {a} → {b}.",
  "selection.edges": "Selected: {count} paths.",
  "selection.group": "Selected: {label} ({kind}).",
  "selection.mixed": "Selected: {count} elements.",
  "menu.title": "Actions for {label}",
  "menu.titlePair": "Actions for {a} and {b}",
  "menu.titleSet": "Actions for {count} activities",
  "menu.group.filter": "Filter",
  "menu.group.explore": "Explore",
  "menu.group.compare": "Compare",
  "menu.group.author": "Author",
  "menu.filterTo": "Filter to cases with this activity",
  "menu.filterToEdge": "Filter to cases with this connection",
  "menu.filterToGroup": "Filter to cases entering this stage",
  "menu.filterToPair": "Filter to cases where {a} is followed by {b}",
  "menu.filterToSet": "Filter to cases containing all selected activities",
  "menu.filterToStart": "Filter to cases starting here",
  "menu.filterToEnd": "Filter to closed cases",
  "menu.exclude": "Exclude cases with this activity",
  "menu.excludeEdge": "Exclude cases with this connection",
  "menu.excludeGroup": "Exclude cases entering this stage",
  "menu.excludePair": "Exclude cases where {a} is followed by {b}",
  "menu.excludeSet": "Exclude cases with any selected activity",
  "menu.excludeEnd": "Filter to open cases",
  "menu.paths": "Paths in and out",
  "menu.pathsEdge": "Path analysis {a} → {b}",
  "menu.pathsPair": "Path between {a} and {b}",
  "menu.pathsGroup": "Paths in and out of the stage",
  "menu.lens": "Distribution lens",
  "menu.lensPair": "Lag between {a} and {b}",
  "menu.addConstraint": "Add expectation here",
  "menu.addConstraintEdge": "Add lag or precedence expectation",
  "menu.addConstraintPair": "Add lag or precedence expectation {a} → {b}",
  "menu.pin": "Pin for comparison",
  "menu.worstCases": "Worst cases through here",
  "menu.worstCasesEdge": "Worst cases on this connection",
  "menu.worstCasesGroup": "Worst cases in this stage",
  "menu.collapse": "Collapse the stage",
  "menu.expand": "Expand the stage",
  "menu.clearFocus": "Hide the paths",
  "menu.opened": "Actions menu for {label} opened; {count} actions.",
  "menu.closed": "Actions menu closed.",
  "menu.announce": "{action}: {target}.",
  "menu.worst": "Worst expectation: {text}",
  "paths.title": "Paths of {label}",
  "paths.titlePair": "Path from {a} to {b}",
  "paths.incoming": "Incoming paths",
  "paths.outgoing": "Outgoing paths",
  "paths.forward": "Path {a} → {b}",
  "paths.reverse": "Reverse path {b} → {a}",
  "paths.from": "From",
  "paths.to": "To",
  "paths.total": "Total",
  "paths.none": "No paths.",
  "paths.notFound": "No path from {a} to {b} in this map.",
  "paths.direct": "direct",
  "paths.source.payload": "numbers from the analysis (full directly-follows graph)",
  "paths.source.graph": "numbers computed from the map at the current abstraction",
  "paths.close": "Close the path list",
  "paths.sortedBy": "sorted by {column}, {direction}",
  "paths.ascending": "ascending",
  "paths.descending": "descending",
  "paths.rows": "{count} paths",
  "filters.title": "Filters",
  "filters.cases": "{in} of {total} cases",
  "filters.out": "{out} removed",
  "filters.remove": "Remove filter: {clause}",
  "filters.clear": "Clear filters",
  "filters.none": "No filters.",
  "filters.marginal": "−{count} by this filter alone",
  "filters.changesCases": "changes cases",
  "filters.added": "Filter added: {clause}.",
  "filters.removed": "Filter removed: {clause}.",
  "filters.cleared": "Filters cleared.",
  "clause.time.case_start": "case start {from} – {to}",
  "clause.time.case_end": "case end {from} – {to}",
  "clause.time.active": "active {from} – {to}",
  "clause.time.events_inside": "events inside {from} – {to}",
  "clause.attribute.in": "{field} in {values}",
  "clause.attribute.not_in": "{field} not in {values}",
  "clause.attribute.range": "{field} between {min} and {max}",
  "clause.attribute.missing": "{field} missing",
  "clause.activity.contains": "cases with {activity}",
  "clause.activity.never": "cases without {activity}",
  "clause.activity.starts_with": "cases starting with {activity}",
  "clause.activity.ends_with": "cases ending with {activity}",
  "clause.follows.directly": "{a} directly followed by {b}",
  "clause.follows.eventually": "{a} eventually followed by {b}",
  "clause.follows.never": "{a} never followed by {b}",
  "clause.lag.min": "lag {a} → {b} at least {value}",
  "clause.lag.max": "lag {a} → {b} at most {value}",
  "clause.lag.range": "lag {a} → {b} between {min} and {max}",
  "clause.count.min": "{activity} at least {min} times",
  "clause.count.max": "{activity} at most {max} times",
  "clause.count.range": "{activity} {min} to {max} times",
  "clause.open.true": "open cases only",
  "clause.open.false": "closed cases only",
  "clause.constraint.violating": "cases violating {constraint}",
  "clause.constraint.satisfied": "cases satisfying {constraint}",
  "clause.constraint.in_scope": "cases in scope of {constraint}",
  "clause.constraint.out_of_scope": "cases outside the scope of {constraint}",
  "clause.slice": "slice {slicing} = {key}",
  "clause.any": "any of: {clauses}",
  "clause.unknown": "filter {kind}",
  "unit.days": "d",
  "unit.hours": "h",
  "unit.minutes": "min",
  "unit.seconds": "s",
  "lanes.title": "Lanes",
  "lanes.stages": "Stage lanes",
  "lanes.roles": "Role lanes",
  "lanes.none": "No lanes",
  "export.png": "Download PNG",
} as const;

export type StringKey = keyof typeof en;

const de: Record<StringKey, string> = {
  "kind.activity": "Aktivität",
  "kind.stage": "Phase",
  "kind.gateway": "Gateway",
  "kind.event": "Ereignis",
  "kind.note": "Notiz",
  "kind.follows": "Pfad",
  "kind.constraint": "Erwartung",
  "kind.flow": "Sequenzfluss",
  "group.lane": "Bahn",
  "group.stage": "Phase",
  "group.pool": "Pool",
  "map.description": "Prozesslandkarte mit {nodes} Aktivitäten und {edges} Pfaden in {groups} Gruppen.",
  "map.abstraction": "Abstraktion: Aktivitäten über {nodeShare}, Pfade über {edgeShare}.",
  "map.overlays": "{count} Erwartungs-Overlays.",
  "map.selected": "Ausgewählt: {label}.",
  "map.reconnected": "wieder eingefügt, damit die Karte zusammenhängt",
  "metric.events": "Ereignisse",
  "metric.cases": "Fälle",
  "metric.count": "Übergänge",
  "metric.share": "Anteil",
  "metric.violationShare": "Erwartungslücke",
  "metric.medianLagHours": "Median-Wartezeit",
  "metric.p90LagHours": "90. Perzentil Wartezeit",
  "metric.medianNextHours": "Median bis zum nächsten Ereignis",
  "metric.starts": "Fallstarts",
  "metric.ends": "Fallenden",
  "metric.internalCount": "Übergänge innerhalb der Phase",
  "metric.members": "Aktivitäten",
  "metric.delta": "Differenz",
  "controls.title": "Abstraktion",
  "controls.activities": "Aktivitäten",
  "controls.paths": "Pfade",
  "controls.collapse": "Phasen zeigen",
  "controls.expand": "Aktivitäten zeigen",
  "controls.connected": "Zusammenhängend halten",
  "controls.table": "Tabellenansicht",
  "controls.map": "Kartenansicht",
  "legend.title": "Legende",
  "legend.edgeWidth": "Pfadbreite",
  "legend.edgeColor": "Pfadfarbe",
  "legend.nodeColor": "Aktivitätsfarbe",
  "legend.reconnected": "Wieder eingefügter Pfad",
  "legend.outOfScope": "Außerhalb des Geltungsbereichs",
  "legend.badge": "Erwartungsmarke mit Lückenanteil",
  "legend.arc": "Bogen für Wartezeit oder Reihenfolge; Breite = Abdeckung, Farbe = Lücke",
  "legend.reverse": "Bogen gegen die erwartete Reihenfolge",
  "legend.selfLoop": "Wiederholte Ausführung",
  "overlay.badge": "Marke",
  "overlay.arc": "Bogen",
  "overlay.hatch": "Schraffur",
  "overlay.tint": "Tönung",
  "overlay.chip": "Chip",
  "overlay.selfLoop": "Schleife",
  "constraint.presence": "Vorkommen",
  "constraint.singularity": "Einmaligkeit",
  "constraint.exclusion": "Ausschluss",
  "constraint.lag": "Wartezeit",
  "constraint.precedence": "Reihenfolge",
  "constraint.balance": "Balance",
  "constraint.metric": "Kennzahl",
  "constraint.applicability": "Geltungsbereich",
  "constraint.missing": "{share} fehlen",
  "constraint.repeated": "{share} wiederholt",
  "constraint.occurs": "{share} treten auf",
  "constraint.late": "{share} zu spät",
  "constraint.reverse": "{share} in umgekehrter Reihenfolge",
  "constraint.coverage": "{share} der Fälle ausgewertet",
  "constraint.median": "Median {value}",
  "constraint.threshold": "Schwelle {value}",
  "constraint.above": "{share} über der Schwelle",
  "constraint.outOfScope": "außerhalb des Geltungsbereichs",
  "constraint.scope": "gilt für {share} der Fälle",
  "constraint.notApplicable": "in dieser Szene nicht anwendbar",
  "table.nodes": "Aktivitäten",
  "table.edges": "Pfade",
  "table.overlays": "Erwartungs-Overlays",
  "table.caption.nodes": "Aktivitäten der Prozesslandkarte mit ihren Kennzahlen",
  "table.caption.edges": "Pfade der Prozesslandkarte mit ihren Kennzahlen",
  "table.caption.overlays": "Erwartungs-Overlays mit den kodierten Zahlen",
  "table.label": "Bezeichnung",
  "table.kind": "Art",
  "table.group": "Gruppe",
  "table.source": "Von",
  "table.target": "Nach",
  "table.overlay": "Overlay",
  "table.target.column": "Ziel",
  "table.constraint": "Erwartung",
  "table.value": "Wert",
  "table.text": "Lesart",
  "table.tags": "Markierungen",
  "table.empty": "Nichts anzuzeigen.",
  "timeline.description": "Fallverlauf mit {traces} Fällen und {events} Ereignissen.",
  "timeline.anchor": "ausgerichtet an {anchor}",
  "timeline.case": "Fall",
  "timeline.time": "Zeit",
  "timeline.activity": "Aktivität",
  "timeline.violates": "Verletzt",
  "timeline.days": "Tage",
  "timeline.hours": "Stunden",
  "export.context": "{label} · {cases} Fälle · {events} Ereignisse",
  "bpmn.description": "BPMN-Diagramm mit {tasks} Aufgaben, {gateways} Gateways und {flows} Sequenzflüssen in {lanes} Bahnen.",
  "bpmn.diagram": "Diagrammansicht",
  "bpmn.table": "Tabellenansicht",
  "bpmn.loading": "Diagramm wird geladen…",
  "bpmn.error": "Das Diagramm konnte nicht geladen werden.",
  "bpmn.selected": "Ausgewählt: {tasks} Aufgaben, {flows} Flüsse, {lanes} Bahnen.",
  "bpmn.mode.view": "Ansehen",
  "bpmn.mode.model": "Modellieren",
  "views.title": "Ansichten",
  "views.single": "Eine Ansicht",
  "views.grid": "Alle Ansichten",
  "views.shared": "Farb- und Breitenskalen gelten für alle Ansichten gemeinsam.",
  "map.instructions": "Pfeiltasten wechseln zwischen Aktivitäten, Leertaste wählt aus, Umschalt mit Pfeiltaste erweitert die Auswahl, Alt mit Pfeiltaste folgt den Pfaden, Eingabe öffnet das Aktionsmenü, Escape hebt die Auswahl auf.",
  "map.focus": "Die Pfade von {label} werden gezeigt; unbeteiligte Aktivitäten sind abgeblendet.",
  "map.focusPair": "Der Pfad zwischen {a} und {b} wird gezeigt; unbeteiligte Aktivitäten sind abgeblendet.",
  "map.renderer.canvas": "Wegen der Größe auf einer Zeichenfläche gezeichnet: {nodes} Aktivitäten und {edges} Pfade.",
  "map.zoomIn": "Vergrößern",
  "map.zoomOut": "Verkleinern",
  "map.fit": "Karte einpassen",
  "map.focused": "Fokus: {label}.",
  "selection.none": "Auswahl aufgehoben.",
  "selection.one": "Ausgewählt: {label}.",
  "selection.pair": "Ausgewählt: {a} und {b}.",
  "selection.set": "Ausgewählt: {count} Aktivitäten: {labels}.",
  "selection.edge": "Ausgewählt: Pfad {a} → {b}.",
  "selection.edges": "Ausgewählt: {count} Pfade.",
  "selection.group": "Ausgewählt: {label} ({kind}).",
  "selection.mixed": "Ausgewählt: {count} Elemente.",
  "menu.title": "Aktionen für {label}",
  "menu.titlePair": "Aktionen für {a} und {b}",
  "menu.titleSet": "Aktionen für {count} Aktivitäten",
  "menu.group.filter": "Filtern",
  "menu.group.explore": "Erkunden",
  "menu.group.compare": "Vergleichen",
  "menu.group.author": "Erfassen",
  "menu.filterTo": "Auf Fälle mit dieser Aktivität filtern",
  "menu.filterToEdge": "Auf Fälle mit diesem Übergang filtern",
  "menu.filterToGroup": "Auf Fälle filtern, die diese Phase erreichen",
  "menu.filterToPair": "Auf Fälle filtern, in denen auf {a} {b} folgt",
  "menu.filterToSet": "Auf Fälle mit allen ausgewählten Aktivitäten filtern",
  "menu.filterToStart": "Auf Fälle filtern, die hier beginnen",
  "menu.filterToEnd": "Auf abgeschlossene Fälle filtern",
  "menu.exclude": "Fälle mit dieser Aktivität ausschließen",
  "menu.excludeEdge": "Fälle mit diesem Übergang ausschließen",
  "menu.excludeGroup": "Fälle ausschließen, die diese Phase erreichen",
  "menu.excludePair": "Fälle ausschließen, in denen auf {a} {b} folgt",
  "menu.excludeSet": "Fälle mit einer der ausgewählten Aktivitäten ausschließen",
  "menu.excludeEnd": "Auf offene Fälle filtern",
  "menu.paths": "Pfade hinein und hinaus",
  "menu.pathsEdge": "Pfadanalyse {a} → {b}",
  "menu.pathsPair": "Pfad zwischen {a} und {b}",
  "menu.pathsGroup": "Pfade in die Phase und aus ihr heraus",
  "menu.lens": "Verteilungslupe",
  "menu.lensPair": "Wartezeit zwischen {a} und {b}",
  "menu.addConstraint": "Erwartung hier hinzufügen",
  "menu.addConstraintEdge": "Wartezeit- oder Reihenfolge-Erwartung hinzufügen",
  "menu.addConstraintPair": "Wartezeit- oder Reihenfolge-Erwartung {a} → {b} hinzufügen",
  "menu.pin": "Zum Vergleich anheften",
  "menu.worstCases": "Schlechteste Fälle durch diese Aktivität",
  "menu.worstCasesEdge": "Schlechteste Fälle auf diesem Übergang",
  "menu.worstCasesGroup": "Schlechteste Fälle in dieser Phase",
  "menu.collapse": "Phase zusammenfassen",
  "menu.expand": "Phase aufklappen",
  "menu.clearFocus": "Pfade ausblenden",
  "menu.opened": "Aktionsmenü für {label} geöffnet; {count} Aktionen.",
  "menu.closed": "Aktionsmenü geschlossen.",
  "menu.announce": "{action}: {target}.",
  "menu.worst": "Größte Erwartungslücke: {text}",
  "paths.title": "Pfade von {label}",
  "paths.titlePair": "Pfad von {a} nach {b}",
  "paths.incoming": "Eingehende Pfade",
  "paths.outgoing": "Ausgehende Pfade",
  "paths.forward": "Pfad {a} → {b}",
  "paths.reverse": "Rückweg {b} → {a}",
  "paths.from": "Von",
  "paths.to": "Nach",
  "paths.total": "Summe",
  "paths.none": "Keine Pfade.",
  "paths.notFound": "Kein Pfad von {a} nach {b} in dieser Karte.",
  "paths.direct": "direkt",
  "paths.source.payload": "Zahlen aus der Analyse (vollständiger Directly-follows-Graph)",
  "paths.source.graph": "Zahlen aus der Karte auf der aktuellen Abstraktionsstufe",
  "paths.close": "Pfadliste schließen",
  "paths.sortedBy": "sortiert nach {column}, {direction}",
  "paths.ascending": "aufsteigend",
  "paths.descending": "absteigend",
  "paths.rows": "{count} Pfade",
  "filters.title": "Filter",
  "filters.cases": "{in} von {total} Fällen",
  "filters.out": "{out} entfernt",
  "filters.remove": "Filter entfernen: {clause}",
  "filters.clear": "Filter löschen",
  "filters.none": "Keine Filter.",
  "filters.marginal": "−{count} allein durch diesen Filter",
  "filters.changesCases": "verändert Fälle",
  "filters.added": "Filter hinzugefügt: {clause}.",
  "filters.removed": "Filter entfernt: {clause}.",
  "filters.cleared": "Filter gelöscht.",
  "clause.time.case_start": "Fallbeginn {from} – {to}",
  "clause.time.case_end": "Fallende {from} – {to}",
  "clause.time.active": "aktiv {from} – {to}",
  "clause.time.events_inside": "Ereignisse innerhalb {from} – {to}",
  "clause.attribute.in": "{field} in {values}",
  "clause.attribute.not_in": "{field} nicht in {values}",
  "clause.attribute.range": "{field} zwischen {min} und {max}",
  "clause.attribute.missing": "{field} fehlt",
  "clause.activity.contains": "Fälle mit {activity}",
  "clause.activity.never": "Fälle ohne {activity}",
  "clause.activity.starts_with": "Fälle, die mit {activity} beginnen",
  "clause.activity.ends_with": "Fälle, die mit {activity} enden",
  "clause.follows.directly": "auf {a} folgt direkt {b}",
  "clause.follows.eventually": "auf {a} folgt irgendwann {b}",
  "clause.follows.never": "auf {a} folgt nie {b}",
  "clause.lag.min": "Wartezeit {a} → {b} mindestens {value}",
  "clause.lag.max": "Wartezeit {a} → {b} höchstens {value}",
  "clause.lag.range": "Wartezeit {a} → {b} zwischen {min} und {max}",
  "clause.count.min": "{activity} mindestens {min}-mal",
  "clause.count.max": "{activity} höchstens {max}-mal",
  "clause.count.range": "{activity} {min}- bis {max}-mal",
  "clause.open.true": "nur offene Fälle",
  "clause.open.false": "nur abgeschlossene Fälle",
  "clause.constraint.violating": "Fälle, die {constraint} verletzen",
  "clause.constraint.satisfied": "Fälle, die {constraint} erfüllen",
  "clause.constraint.in_scope": "Fälle im Geltungsbereich von {constraint}",
  "clause.constraint.out_of_scope": "Fälle außerhalb des Geltungsbereichs von {constraint}",
  "clause.slice": "Ausschnitt {slicing} = {key}",
  "clause.any": "eines von: {clauses}",
  "clause.unknown": "Filter {kind}",
  "unit.days": "T",
  "unit.hours": "h",
  "unit.minutes": "min",
  "unit.seconds": "s",
  "lanes.title": "Bahnen",
  "lanes.stages": "Phasenbahnen",
  "lanes.roles": "Rollenbahnen",
  "lanes.none": "Keine Bahnen",
  "export.png": "PNG herunterladen",
};

export const strings: Record<Locale, Record<StringKey, string>> = { en, de };

/** Translate a key with `{placeholder}` substitution. Unknown keys return the key. */
export function t(locale: Locale, key: StringKey, vars: Record<string, string | number> = {}): string {
  const template = strings[locale]?.[key] ?? strings.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => (vars[name] !== undefined ? String(vars[name]) : `{${name}}`));
}

/** Human label of a metric name; unknown metrics are returned verbatim. */
export function metricLabel(locale: Locale, name: string): string {
  const key = `metric.${name}` as StringKey;
  if (strings.en[key]) return t(locale, key);
  if (name.startsWith("delta_")) return `${t(locale, "metric.delta")} ${metricLabel(locale, name.slice(6))}`;
  if (name.startsWith("a_")) return `${metricLabel(locale, name.slice(2))} (a)`;
  return name;
}
