/**
 * User-visible strings of the core and the renderers. English is complete;
 * German covers the same keys. Vocabulary follows the workbench rules:
 * "priority", "expectation shortfall", never "root cause", "fault" or "effect".
 */
import type { Locale } from "./format";

const en = {
  "kind.activity": "activity",
  "kind.stage": "stage",
  "kind.gateway": "gateway",
  "kind.event": "event",
  "kind.note": "note",
  "kind.follows": "path",
  "kind.constraint": "constraint",
  "kind.flow": "sequence flow",
  "group.lane": "lane",
  "group.stage": "stage",
  "group.pool": "pool",
  "map.description": "Process map with {nodes} activities and {edges} paths in {groups} groups.",
  "map.abstraction": "Abstraction: activities above {nodeShare}, paths above {edgeShare}.",
  "map.overlays": "{count} constraint overlays.",
  "map.instructions": "Use the arrow keys to move between activities, Enter to select, Escape to clear the selection.",
  "map.selected": "Selected: {label}.",
  "map.reconnected": "re-added to keep the map connected",
  "metric.events": "events",
  "metric.cases": "cases",
  "metric.count": "transitions",
  "metric.share": "share",
  "metric.violationShare": "expectation shortfall",
  "metric.medianLagHours": "median lag",
  "metric.p90LagHours": "90th percentile lag",
  "metric.medianNextHours": "median time to next event",
  "metric.starts": "case starts",
  "metric.ends": "case ends",
  "metric.internalCount": "transitions inside the stage",
  "metric.members": "activities",
  "metric.delta": "difference",
  "controls.title": "Abstraction",
  "controls.activities": "Activities",
  "controls.paths": "Paths",
  "controls.collapse": "Show stages",
  "controls.expand": "Show activities",
  "controls.connected": "Keep connected",
  "controls.table": "Table view",
  "controls.map": "Map view",
  "legend.title": "Legend",
  "legend.edgeWidth": "Path width",
  "legend.edgeColor": "Path colour",
  "legend.nodeColor": "Activity colour",
  "legend.reconnected": "Re-added path",
  "legend.outOfScope": "Outside scope",
  "legend.badge": "Constraint badge with shortfall share",
  "legend.arc": "Lag or precedence arc; width = coverage, colour = shortfall",
  "legend.reverse": "Reverse-order arc (precedence violated)",
  "legend.selfLoop": "Repeated execution",
  "overlay.badge": "badge",
  "overlay.arc": "arc",
  "overlay.hatch": "hatch",
  "overlay.tint": "tint",
  "overlay.chip": "chip",
  "overlay.selfLoop": "self-loop",
  "constraint.presence": "presence",
  "constraint.singularity": "singularity",
  "constraint.exclusion": "exclusion",
  "constraint.lag": "lag",
  "constraint.precedence": "precedence",
  "constraint.balance": "balance",
  "constraint.metric": "metric",
  "constraint.applicability": "applicability",
  "constraint.missing": "{share} missing",
  "constraint.repeated": "{share} repeated",
  "constraint.occurs": "{share} occur",
  "constraint.late": "{share} late",
  "constraint.reverse": "{share} in reverse order",
  "constraint.coverage": "{share} of cases evaluated",
  "constraint.median": "median {value}",
  "constraint.threshold": "threshold {value}",
  "constraint.above": "{share} above threshold",
  "constraint.outOfScope": "outside scope",
  "constraint.scope": "applies to {share} of cases",
  "constraint.notApplicable": "not applicable in this scene",
  "table.nodes": "Activities",
  "table.edges": "Paths",
  "table.overlays": "Constraint overlays",
  "table.caption.nodes": "Activities of the process map with their metrics",
  "table.caption.edges": "Paths of the process map with their metrics",
  "table.caption.overlays": "Constraint overlays with the numbers they encode",
  "table.label": "Label",
  "table.kind": "Kind",
  "table.group": "Group",
  "table.source": "From",
  "table.target": "To",
  "table.overlay": "Overlay",
  "table.target.column": "Target",
  "table.constraint": "Constraint",
  "table.value": "Value",
  "table.text": "Reading",
  "table.tags": "Tags",
  "table.empty": "Nothing to show.",
  "timeline.description": "Trace timeline with {traces} cases and {events} events.",
  "timeline.anchor": "aligned at {anchor}",
  "timeline.case": "Case",
  "timeline.time": "Time",
  "timeline.activity": "Activity",
  "timeline.violates": "Violates",
  "timeline.days": "days",
  "timeline.hours": "hours",
  "export.context": "{label} · {cases} cases · {events} events",
  "bpmn.description": "BPMN diagram with {tasks} tasks, {gateways} gateways and {flows} sequence flows in {lanes} lanes.",
  "bpmn.diagram": "Diagram view",
  "bpmn.table": "Table view",
  "bpmn.loading": "Loading the diagram…",
  "bpmn.error": "The diagram could not be loaded.",
  "bpmn.selected": "Selected: {tasks} tasks, {flows} flows, {lanes} lanes.",
  "bpmn.mode.view": "View",
  "bpmn.mode.model": "Model",
  "views.title": "Views",
  "views.single": "One view",
  "views.grid": "All views",
  "views.shared": "Colour and width scales are shared across the views.",
} as const;

export type StringKey = keyof typeof en;

const de: Record<StringKey, string> = {
  "kind.activity": "Aktivität",
  "kind.stage": "Phase",
  "kind.gateway": "Gateway",
  "kind.event": "Ereignis",
  "kind.note": "Notiz",
  "kind.follows": "Pfad",
  "kind.constraint": "Erwartung",
  "kind.flow": "Sequenzfluss",
  "group.lane": "Bahn",
  "group.stage": "Phase",
  "group.pool": "Pool",
  "map.description": "Prozesslandkarte mit {nodes} Aktivitäten und {edges} Pfaden in {groups} Gruppen.",
  "map.abstraction": "Abstraktion: Aktivitäten über {nodeShare}, Pfade über {edgeShare}.",
  "map.overlays": "{count} Erwartungs-Overlays.",
  "map.instructions": "Pfeiltasten wechseln zwischen Aktivitäten, Eingabe wählt aus, Escape hebt die Auswahl auf.",
  "map.selected": "Ausgewählt: {label}.",
  "map.reconnected": "wieder eingefügt, damit die Karte zusammenhängt",
  "metric.events": "Ereignisse",
  "metric.cases": "Fälle",
  "metric.count": "Übergänge",
  "metric.share": "Anteil",
  "metric.violationShare": "Erwartungslücke",
  "metric.medianLagHours": "Median-Wartezeit",
  "metric.p90LagHours": "90. Perzentil Wartezeit",
  "metric.medianNextHours": "Median bis zum nächsten Ereignis",
  "metric.starts": "Fallstarts",
  "metric.ends": "Fallenden",
  "metric.internalCount": "Übergänge innerhalb der Phase",
  "metric.members": "Aktivitäten",
  "metric.delta": "Differenz",
  "controls.title": "Abstraktion",
  "controls.activities": "Aktivitäten",
  "controls.paths": "Pfade",
  "controls.collapse": "Phasen zeigen",
  "controls.expand": "Aktivitäten zeigen",
  "controls.connected": "Zusammenhängend halten",
  "controls.table": "Tabellenansicht",
  "controls.map": "Kartenansicht",
  "legend.title": "Legende",
  "legend.edgeWidth": "Pfadbreite",
  "legend.edgeColor": "Pfadfarbe",
  "legend.nodeColor": "Aktivitätsfarbe",
  "legend.reconnected": "Wieder eingefügter Pfad",
  "legend.outOfScope": "Außerhalb des Geltungsbereichs",
  "legend.badge": "Erwartungsmarke mit Lückenanteil",
  "legend.arc": "Bogen für Wartezeit oder Reihenfolge; Breite = Abdeckung, Farbe = Lücke",
  "legend.reverse": "Bogen gegen die erwartete Reihenfolge",
  "legend.selfLoop": "Wiederholte Ausführung",
  "overlay.badge": "Marke",
  "overlay.arc": "Bogen",
  "overlay.hatch": "Schraffur",
  "overlay.tint": "Tönung",
  "overlay.chip": "Chip",
  "overlay.selfLoop": "Schleife",
  "constraint.presence": "Vorkommen",
  "constraint.singularity": "Einmaligkeit",
  "constraint.exclusion": "Ausschluss",
  "constraint.lag": "Wartezeit",
  "constraint.precedence": "Reihenfolge",
  "constraint.balance": "Balance",
  "constraint.metric": "Kennzahl",
  "constraint.applicability": "Geltungsbereich",
  "constraint.missing": "{share} fehlen",
  "constraint.repeated": "{share} wiederholt",
  "constraint.occurs": "{share} treten auf",
  "constraint.late": "{share} zu spät",
  "constraint.reverse": "{share} in umgekehrter Reihenfolge",
  "constraint.coverage": "{share} der Fälle ausgewertet",
  "constraint.median": "Median {value}",
  "constraint.threshold": "Schwelle {value}",
  "constraint.above": "{share} über der Schwelle",
  "constraint.outOfScope": "außerhalb des Geltungsbereichs",
  "constraint.scope": "gilt für {share} der Fälle",
  "constraint.notApplicable": "in dieser Szene nicht anwendbar",
  "table.nodes": "Aktivitäten",
  "table.edges": "Pfade",
  "table.overlays": "Erwartungs-Overlays",
  "table.caption.nodes": "Aktivitäten der Prozesslandkarte mit ihren Kennzahlen",
  "table.caption.edges": "Pfade der Prozesslandkarte mit ihren Kennzahlen",
  "table.caption.overlays": "Erwartungs-Overlays mit den kodierten Zahlen",
  "table.label": "Bezeichnung",
  "table.kind": "Art",
  "table.group": "Gruppe",
  "table.source": "Von",
  "table.target": "Nach",
  "table.overlay": "Overlay",
  "table.target.column": "Ziel",
  "table.constraint": "Erwartung",
  "table.value": "Wert",
  "table.text": "Lesart",
  "table.tags": "Markierungen",
  "table.empty": "Nichts anzuzeigen.",
  "timeline.description": "Fallverlauf mit {traces} Fällen und {events} Ereignissen.",
  "timeline.anchor": "ausgerichtet an {anchor}",
  "timeline.case": "Fall",
  "timeline.time": "Zeit",
  "timeline.activity": "Aktivität",
  "timeline.violates": "Verletzt",
  "timeline.days": "Tage",
  "timeline.hours": "Stunden",
  "export.context": "{label} · {cases} Fälle · {events} Ereignisse",
  "bpmn.description": "BPMN-Diagramm mit {tasks} Aufgaben, {gateways} Gateways und {flows} Sequenzflüssen in {lanes} Bahnen.",
  "bpmn.diagram": "Diagrammansicht",
  "bpmn.table": "Tabellenansicht",
  "bpmn.loading": "Diagramm wird geladen…",
  "bpmn.error": "Das Diagramm konnte nicht geladen werden.",
  "bpmn.selected": "Ausgewählt: {tasks} Aufgaben, {flows} Flüsse, {lanes} Bahnen.",
  "bpmn.mode.view": "Ansehen",
  "bpmn.mode.model": "Modellieren",
  "views.title": "Ansichten",
  "views.single": "Eine Ansicht",
  "views.grid": "Alle Ansichten",
  "views.shared": "Farb- und Breitenskalen gelten für alle Ansichten gemeinsam.",
};

export const strings: Record<Locale, Record<StringKey, string>> = { en, de };

/** Translate a key with `{placeholder}` substitution. Unknown keys return the key. */
export function t(locale: Locale, key: StringKey, vars: Record<string, string | number> = {}): string {
  const template = strings[locale]?.[key] ?? strings.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => (vars[name] !== undefined ? String(vars[name]) : `{${name}}`));
}

/** Human label of a metric name; unknown metrics are returned verbatim. */
export function metricLabel(locale: Locale, name: string): string {
  const key = `metric.${name}` as StringKey;
  if (strings.en[key]) return t(locale, key);
  if (name.startsWith("delta_")) return `${t(locale, "metric.delta")} ${metricLabel(locale, name.slice(6))}`;
  if (name.startsWith("a_")) return `${metricLabel(locale, name.slice(2))} (a)`;
  return name;
}
